version: "2.4"
services:
  backend:
    image: sungjin0757/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m
    environment:
      MYSQL_HOST: docker-application-mysql.ce5wgqxt8e5z.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: sungjin0757
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306

  frontend:
    image: sungjin0757/docker-frontend
    volumes:
      - /app/node_modules
      - ./front-end:/app
    stdin_open: true
    mem_limit: 128m

  # mysql:
  #   build: ./mysql
  #   restart: always
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: myapp
      

  nginx:
    restart: always
    image: sungjin0757/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend